"""
generate_images.py
Mint-YT-Factory

Version 8.0

AI Visual Generation Engine

Pipeline:

generate_script.py
        ↓
Gemini research-backed storyboard
        ↓
Visual identity + continuity locks
        ↓
Semantic image prompts
        ↓
Pollinations AI
        ↓
Validated PNG visuals
        ↓
assemble.py

CORE GOAL
---------
Create 14 visually coherent AI-generated images for one
45-second YouTube Short.

The images must feel like they belong to ONE story,
not 14 unrelated AI generations.

FEATURES
--------
- Exactly 7 scenes
- Exactly 2 visuals per scene
- Exactly 14 images
- 9:16 portrait output
- Deterministic base seed
- Unique shot seeds
- Visual identity lock
- Recurring subject continuity
- Recurring object continuity
- Environment continuity
- Scene-to-scene visual continuity
- Shot progression
- Automatic retries
- HTTP/image validation
- PIL integrity validation
- PNG normalization
- Compatible with main.py
- Compatible with assemble.py
- No stock footage
- No text/captions/logos requested in image prompts
"""


import os
import time
import urllib.parse

import requests

try:
    from PIL import Image
    from io import BytesIO
except ImportError:
    Image = None
    BytesIO = None


# ==========================================================================
# CONFIGURATION
# ==========================================================================

BASE_URL = "https://image.pollinations.ai/prompt/"

MODEL_NAME = "flux"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 "
        "(Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 "
        "(KHTML, like Gecko) "
        "Chrome/140.0 Safari/537.36"
    ),
    "Accept": (
        "image/png,"
        "image/jpeg,"
        "image/webp,"
        "*/*"
    ),
}

# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------

MAX_RETRIES = 5
RETRY_DELAY = 5

REQUEST_TIMEOUT = 180
BETWEEN_IMAGE_DELAY = 2

# --------------------------------------------------------------------------
# Production contract
# --------------------------------------------------------------------------

DEFAULT_WIDTH = 768
DEFAULT_HEIGHT = 1365

EXPECTED_SCENES = 7
VISUALS_PER_SCENE = 2
EXPECTED_TOTAL_IMAGES = 14

# --------------------------------------------------------------------------
# Image validation
# --------------------------------------------------------------------------

MIN_IMAGE_BYTES = 10_000

# Images are ultimately normalized to PNG.
EXPECTED_FORMAT = "PNG"

# --------------------------------------------------------------------------
# Prompt limits
#
# These are not hard limits on Pollinations.
# They prevent continuity metadata from becoming absurdly large.
# --------------------------------------------------------------------------

MAX_RECURRING_SUBJECTS = 4
MAX_RECURRING_OBJECTS = 5
MAX_CONTINUITY_RULES = 5

MAX_STYLE_LENGTH = 500
MAX_PALETTE_LENGTH = 300
MAX_MOOD_LENGTH = 300
MAX_ENVIRONMENT_LENGTH = 500

MAX_PROMPT_LENGTH = 1800


# ==========================================================================
# BASIC HELPERS
# ==========================================================================

def _clean_prompt(text):
    """
    Normalize prompt whitespace without changing its meaning.
    """

    if not text:
        return ""

    text = str(text)

    text = text.replace(
        "\n",
        " ",
    )

    text = text.replace(
        "```",
        "",
    )

    text = " ".join(
        text.split()
    )

    return text.strip()


def _clean_text(
    value,
    maximum=None,
):
    """
    Clean ordinary metadata text.
    """

    if value is None:
        return ""

    value = " ".join(
        str(value).split()
    ).strip()

    if maximum:
        value = value[:maximum]

    return value


def _safe_int(
    value,
    default,
):
    try:
        return int(value)
    except (
        TypeError,
        ValueError,
    ):
        return default


# ==========================================================================
# VISUAL IDENTITY
# ==========================================================================

def _get_visual_identity(
    script,
):
    """
    Extract the global visual identity generated by Gemini.

    This is now ACTUALLY used during image generation.

    Expected structure:

    visual_identity:
        style
        palette
        mood_arc
    """

    identity = script.get(
        "visual_identity",
        {},
    )

    if not isinstance(
        identity,
        dict,
    ):
        identity = {}

    style = _clean_text(
        identity.get(
            "style",
            "",
        ),
        MAX_STYLE_LENGTH,
    )

    palette = _clean_text(
        identity.get(
            "palette",
            "",
        ),
        MAX_PALETTE_LENGTH,
    )

    mood_arc = _clean_text(
        identity.get(
            "mood_arc",
            "",
        ),
        MAX_MOOD_LENGTH,
    )

    return {
        "style": style,
        "palette": palette,
        "mood_arc": mood_arc,
    }


# ==========================================================================
# VISUAL CONTINUITY
# ==========================================================================

def _get_visual_continuity(
    script,
):
    """
    Extract recurring visual subjects, objects,
    environment and continuity rules.

    This is the major continuity layer.

    The image provider itself does not know what appeared
    in previous scenes.

    Therefore we explicitly carry the visual identity forward
    in every relevant prompt.
    """

    continuity = script.get(
        "visual_continuity",
        {},
    )

    if not isinstance(
        continuity,
        dict,
    ):
        continuity = {}

    subjects = continuity.get(
        "recurring_subjects",
        [],
    )

    if not isinstance(
        subjects,
        list,
    ):
        subjects = []

    normalized_subjects = []

    for subject in subjects[
        :MAX_RECURRING_SUBJECTS
    ]:

        if not isinstance(
            subject,
            dict,
        ):
            continue

        name = _clean_text(
            subject.get(
                "name",
                "",
            ),
            100,
        )

        appearance = _clean_text(
            subject.get(
                "appearance",
                "",
            ),
            500,
        )

        continuity_rule = _clean_text(
            subject.get(
                "continuity",
                "",
            ),
            300,
        )

        if not name or not appearance:
            continue

        normalized_subjects.append({
            "name": name,
            "appearance": appearance,
            "continuity": (
                continuity_rule
                or
                "keep the same appearance throughout the story"
            ),
        })

    objects = continuity.get(
        "recurring_objects",
        [],
    )

    if not isinstance(
        objects,
        list,
    ):
        objects = []

    normalized_objects = []

    for item in objects[
        :MAX_RECURRING_OBJECTS
    ]:

        item = _clean_text(
            item,
            200,
        )

        if item:
            normalized_objects.append(
                item
            )

    environment = _clean_text(
        continuity.get(
            "recurring_environment",
            "",
        ),
        MAX_ENVIRONMENT_LENGTH,
    )

    rules = continuity.get(
        "continuity_rules",
        [],
    )

    if not isinstance(
        rules,
        list,
    ):
        rules = []

    normalized_rules = []

    for rule in rules[
        :MAX_CONTINUITY_RULES
    ]:

        rule = _clean_text(
            rule,
            300,
        )

        if rule:
            normalized_rules.append(
                rule
            )

    return {
        "subjects": normalized_subjects,
        "objects": normalized_objects,
        "environment": environment,
        "rules": normalized_rules,
    }


# ==========================================================================
# IMAGE GENERATION METADATA
# ==========================================================================

def _get_image_generation_config(
    script,
):
    """
    Read deterministic generation metadata from generate_script.py.
    """

    generation = script.get(
        "image_generation",
        {},
    )

    if not isinstance(
        generation,
        dict,
    ):
        generation = {}

    try:
        seed = int(
            generation.get(
                "seed",
                int(time.time()),
            )
        )
    except Exception:
        seed = int(time.time())

    style_lock = _clean_text(
        generation.get(
            "style_lock",
            "",
        ),
        1000,
    )

    return {
        "seed": seed,
        "style_lock": style_lock,
    }


# ==========================================================================
# SEED MANAGEMENT
# ==========================================================================

def _get_base_seed(
    script,
):
    """
    Get the deterministic seed generated by generate_script.py.
    """

    generation = _get_image_generation_config(
        script
    )

    return generation["seed"]


def _get_shot_seed(
    base_seed,
    scene_index,
    visual_index,
    attempt=0,
):
    """
    Generate a deterministic seed for each shot.

    Normal generation:

        same script
        same base seed
        same scene
        same shot
        → same seed

    Retry:

        attempt > 0
        → deterministic alternate seed

    This prevents repeated retries from repeatedly requesting
    exactly the same failed generation.
    """

    base = (
        base_seed
        + (scene_index * 100)
        + visual_index
    )

    if attempt <= 0:
        return base

    return (
        base
        + (attempt * 10_000)
    )


# ==========================================================================
# SHOT CONTEXT
# ==========================================================================

def _get_scene_context(
    scene,
):
    """
    Extract scene-level information useful for continuity.
    """

    if not isinstance(
        scene,
        dict,
    ):
        return {}

    return {
        "emotional_tone": _clean_text(
            scene.get(
                "emotional_tone",
                "",
            ),
            100,
        ),

        "visual_priority": _clean_text(
            scene.get(
                "visual_priority",
                "",
            ),
            100,
        ),

        "transition": _clean_text(
            scene.get(
                "transition",
                "",
            ),
            100,
        ),
    }


# ==========================================================================
# PROMPT COMPONENTS
# ==========================================================================

def _build_identity_block(
    script,
):
    """
    Build a concise global visual identity block.
    """

    identity = _get_visual_identity(
        script
    )

    parts = []

    if identity["style"]:
        parts.append(
            f"Visual style: {identity['style']}."
        )

    if identity["palette"]:
        parts.append(
            f"Color palette: {identity['palette']}."
        )

    if identity["mood_arc"]:
        parts.append(
            f"Overall mood: {identity['mood_arc']}."
        )

    return " ".join(
        parts
    )


def _build_subject_block(
    script,
):
    """
    Build recurring-subject continuity instructions.
    """

    continuity = _get_visual_continuity(
        script
    )

    subjects = continuity[
        "subjects"
    ]

    if not subjects:
        return ""

    parts = [
        "Continuity characters and subjects:"
    ]

    for subject in subjects:

        parts.append(
            (
                f"{subject['name']}: "
                f"{subject['appearance']}. "
                f"{subject['continuity']}."
            )
        )

    return " ".join(
        parts
    )


def _build_object_block(
    script,
):
    """
    Build recurring-object continuity instructions.
    """

    continuity = _get_visual_continuity(
        script
    )

    objects = continuity[
        "objects"
    ]

    if not objects:
        return ""

    return (
        "Recurring objects: "
        + "; ".join(objects)
        + ". Keep their appearance consistent."
    )


def _build_environment_block(
    script,
):
    """
    Build recurring-environment continuity instructions.
    """

    continuity = _get_visual_continuity(
        script
    )

    environment = continuity[
        "environment"
    ]

    if not environment:
        return ""

    return (
        "Recurring environment: "
        + environment
        + ". Maintain its visual identity."
    )


def _build_rules_block(
    script,
):
    """
    Build explicit continuity rules.
    """

    continuity = _get_visual_continuity(
        script
    )

    rules = continuity[
        "rules"
    ]

    if not rules:
        return ""

    return (
        "Continuity rules: "
        + "; ".join(rules)
        + "."
    )


# ==========================================================================
# PREVIOUS SHOT CONTEXT
# ==========================================================================

def _build_previous_shot_context(
    scene,
    visual_index,
):
    """
    Give Shot 2 a conceptual relationship to Shot 1.

    We deliberately do NOT copy Shot 1's prompt wholesale.

    Shot 2 must remain visually distinct while belonging
    to the same moment.
    """

    if visual_index <= 1:
        return ""

    visuals = scene.get(
        "visuals",
        [],
    )

    if not isinstance(
        visuals,
        list,
    ):
        return ""

    if len(visuals) < 1:
        return ""

    previous = visuals[0]

    if not isinstance(
        previous,
        dict,
    ):
        return ""

    previous_prompt = _clean_prompt(
        previous.get(
            "image_prompt",
            "",
        )
    )

    if not previous_prompt:
        return ""

    # Keep this compact.
    previous_prompt = previous_prompt[
        :500
    ]

    return (
        "This is the second shot of the same scene. "
        "Keep the same subjects, environment and visual identity "
        "while advancing the moment rather than repeating the first shot. "
        f"First-shot visual context: {previous_prompt}"
    )


# ==========================================================================
# BUILD IMAGE PROMPT
# ==========================================================================

def build_prompt(
    scene,
    visual,
    script=None,
    scene_index=1,
    visual_index=1,
):
    """
    Build the final Pollinations prompt.

    IMPORTANT:

    Gemini's image_prompt remains the PRIMARY semantic description.

    We add only production continuity information around it.

    We do NOT add:
    - narration
    - subtitles
    - captions
    - YouTube instructions
    - aspect ratio
    - negative prompts
    - camera commands
    - artificial prompt spam
    """

    if not isinstance(
        visual,
        dict,
    ):
        raise RuntimeError(
            f"Scene {scene_index} visual "
            f"{visual_index} is invalid."
        )

    semantic_prompt = _clean_prompt(
        visual.get(
            "image_prompt",
            "",
        )
    )

    if not semantic_prompt:
        raise RuntimeError(
            f"Scene {scene_index} visual "
            f"{visual_index} has an empty image_prompt."
        )

    if not isinstance(
        script,
        dict,
    ):
        script = {}

    identity_block = _build_identity_block(
        script
    )

    subject_block = _build_subject_block(
        script
    )

    object_block = _build_object_block(
        script
    )

    environment_block = _build_environment_block(
        script
    )

    rules_block = _build_rules_block(
        script
    )

    previous_shot_block = _build_previous_shot_context(
        scene,
        visual_index,
    )

    scene_context = _get_scene_context(
        scene
    )

    parts = []

    # ----------------------------------------------------------------------
    # PRIMARY VISUAL DESCRIPTION
    # ----------------------------------------------------------------------

    parts.append(
        semantic_prompt
    )

    # ----------------------------------------------------------------------
    # GLOBAL VISUAL IDENTITY
    # ----------------------------------------------------------------------

    if identity_block:

        parts.append(
            identity_block
        )

    # ----------------------------------------------------------------------
    # RECURRING SUBJECTS
    # ----------------------------------------------------------------------

    if subject_block:

        parts.append(
            subject_block
        )

    # ----------------------------------------------------------------------
    # RECURRING OBJECTS
    # ----------------------------------------------------------------------

    if object_block:

        parts.append(
            object_block
        )

    # ----------------------------------------------------------------------
    # ENVIRONMENT
    # ----------------------------------------------------------------------

    if environment_block:

        parts.append(
            environment_block
        )

    # ----------------------------------------------------------------------
    # CONTINUITY RULES
    # ----------------------------------------------------------------------

    if rules_block:

        parts.append(
            rules_block
        )

    # ----------------------------------------------------------------------
    # SECOND-SHOT RELATIONSHIP
    # ----------------------------------------------------------------------

    if previous_shot_block:

        parts.append(
            previous_shot_block
        )

    # ----------------------------------------------------------------------
    # Scene-level emotional context
    # ----------------------------------------------------------------------

    if scene_context.get(
        "emotional_tone"
    ):

        parts.append(
            (
                "Scene emotional tone: "
                f"{scene_context['emotional_tone']}."
            )
        )

    # ----------------------------------------------------------------------
    # Visual distinction
    # ----------------------------------------------------------------------

    if visual_index == 1:

        parts.append(
            "This shot establishes the scene."
        )

    else:

        parts.append(
            "This shot advances or reveals the next visual beat."
        )

    final_prompt = _clean_prompt(
        " ".join(parts)
    )

    if len(
        final_prompt
    ) > MAX_PROMPT_LENGTH:

        final_prompt = final_prompt[
            :MAX_PROMPT_LENGTH
        ]

        # Avoid ending in a broken word where possible.
        final_prompt = final_prompt.rsplit(
            " ",
            1,
        )[0]

    return final_prompt


# ==========================================================================
# IMAGE URL
# ==========================================================================

def _build_image_url(
    prompt,
    width,
    height,
    seed,
):
    """
    Build Pollinations image URL.
    """

    encoded_prompt = urllib.parse.quote(
        prompt,
        safe="",
    )

    url = (
        BASE_URL
        + encoded_prompt
        + f"?model={MODEL_NAME}"
        + f"&width={int(width)}"
        + f"&height={int(height)}"
        + f"&seed={int(seed)}"
        + "&enhance=true"
        + "&nologo=true"
    )

    return url


# ==========================================================================
# HTTP RESPONSE VALIDATION
# ==========================================================================

def _validate_image_response(
    response,
):
    """
    Validate that the provider returned actual image data.
    """

    if response is None:

        raise RuntimeError(
            "Empty HTTP response."
        )

    if response.status_code != 200:

        preview = response.text[
            :300
        ] if response.text else ""

        raise RuntimeError(
            f"HTTP {response.status_code}: "
            f"{preview}"
        )

    content = response.content

    if not content:

        raise RuntimeError(
            "Image response was empty."
        )

    if len(content) < MIN_IMAGE_BYTES:

        raise RuntimeError(
            "Image response is suspiciously small."
        )

    content_type = (
        response.headers.get(
            "Content-Type",
            "",
        )
        .lower()
    )

    image_signatures = (
        b"\x89PNG",
        b"\xff\xd8\xff",
        b"RIFF",
    )

    has_image_content_type = (
        "image" in content_type
    )

    has_image_signature = any(
        content.startswith(
            signature
        )
        for signature in image_signatures
    )

    if (
        not has_image_content_type
        and
        not has_image_signature
    ):

        preview = content[
            :300
        ]

        try:

            preview = preview.decode(
                "utf-8",
                errors="ignore",
            )

        except Exception:

            preview = "<binary response>"

        raise RuntimeError(
            "Server returned a non-image response: "
            f"{preview}"
        )

    return content


# ==========================================================================
# PIL IMAGE VALIDATION
# ==========================================================================

def _validate_with_pillow(
    content,
    expected_width,
    expected_height,
):
    """
    Open the generated image with Pillow.

    This catches:
    - corrupted image files
    - fake image responses
    - unreadable image data
    - invalid dimensions
    """

    if Image is None:

        # Pillow is useful but not allowed to prevent
        # the pipeline from working if it is absent.
        return content

    try:

        image = Image.open(
            BytesIO(content)
        )

        image.verify()

        # Reopen because verify() invalidates the image object.
        image = Image.open(
            BytesIO(content)
        )

        actual_width, actual_height = (
            image.size
        )

        if actual_width <= 0 or actual_height <= 0:

            raise RuntimeError(
                "Generated image has invalid dimensions."
            )

        # We do not reject provider dimensions here because
        # some providers may return slightly different dimensions.
        #
        # The final saved image will be normalized to the requested
        # portrait dimensions.

        return content

    except Exception as error:

        raise RuntimeError(
            f"Pillow could not validate generated image: "
            f"{error}"
        )


# ==========================================================================
# IMAGE REQUEST
# ==========================================================================

def generate_image(
    prompt,
    width,
    height,
    seed,
):
    """
    Generate one image through Pollinations.

    Retry behavior:
    - transient HTTP/provider failure → retry
    - invalid image → retry
    - retry receives a deterministic alternate seed
    """

    prompt = _clean_prompt(
        prompt
    )

    if not prompt:

        raise RuntimeError(
            "Cannot generate an image "
            "with an empty prompt."
        )

    last_error = None

    session = requests.Session()

    session.headers.update(
        HEADERS
    )

    try:

        for attempt in range(
            0,
            MAX_RETRIES,
        ):

            attempt_seed = _get_retry_seed_from_original(
                seed,
                attempt,
            )

            url = _build_image_url(
                prompt,
                width,
                height,
                attempt_seed,
            )

            print("=" * 80)
            print("IMAGE GENERATION REQUEST")
            print("=" * 80)

            print(
                f"Attempt: {attempt + 1}/{MAX_RETRIES}"
            )

            print(
                f"Seed: {attempt_seed}"
            )

            print(
                f"Size: {width}x{height}"
            )

            print(
                f"Prompt length: {len(prompt)}"
            )

            print(
                f"Prompt: {prompt}"
            )

            print("=" * 80)

            try:

                print(
                    f"🎨 Image attempt "
                    f"{attempt + 1}/{MAX_RETRIES}"
                )

                response = session.get(
                    url,
                    timeout=REQUEST_TIMEOUT,
                )

                print(
                    f"HTTP status: "
                    f"{response.status_code}"
                )

                content = _validate_image_response(
                    response
                )

                content = _validate_with_pillow(
                    content,
                    width,
                    height,
                )

                print(
                    f"Image bytes: "
                    f"{len(content):,}"
                )

                print(
                    "✅ Image generated successfully."
                )

                return content

            except Exception as error:

                last_error = error

                print(
                    f"❌ Image attempt "
                    f"{attempt + 1} failed:"
                )

                print(
                    f"{type(error).__name__}: "
                    f"{error}"
                )

                if (
                    attempt
                    <
                    MAX_RETRIES - 1
                ):

                    print(
                        f"⏳ Retrying in "
                        f"{RETRY_DELAY} seconds..."
                    )

                    time.sleep(
                        RETRY_DELAY
                    )

    finally:

        session.close()

    raise RuntimeError(
        "Failed to generate image after "
        f"{MAX_RETRIES} attempts: "
        f"{last_error}"
    )


def _get_retry_seed_from_original(
    original_seed,
    attempt,
):
    """
    Generate deterministic alternate seeds for retries.

    Attempt 0:
        original seed

    Attempt 1:
        original + 10000

    Attempt 2:
        original + 20000

    etc.
    """

    if attempt <= 0:

        return int(
            original_seed
        )

    return (
        int(original_seed)
        + (
            attempt
            * 10_000
        )
    )


# ==========================================================================
# SAVE / NORMALIZE IMAGE
# ==========================================================================

def _save_image(
    content,
    path,
    width,
    height,
):
    """
    Save generated content as a genuine PNG.

    If Pollinations returns JPEG/WebP/etc.,
    Pillow converts it to PNG.

    The rest of the pipeline therefore always receives:

        .png
    """

    if not content:

        raise RuntimeError(
            "Cannot save empty image content."
        )

    output_dir = os.path.dirname(
        path
    )

    if output_dir:

        os.makedirs(
            output_dir,
            exist_ok=True,
        )

    # ----------------------------------------------------------------------
    # Pillow normalization
    # ----------------------------------------------------------------------

    if Image is not None:

        try:

            image = Image.open(
                BytesIO(content)
            )

            image.load()

            # --------------------------------------------------------------
            # Normalize color mode.
            # --------------------------------------------------------------

            if image.mode not in (
                "RGB",
                "RGBA",
            ):

                image = image.convert(
                    "RGB"
                )

            # --------------------------------------------------------------
            # Resize to requested dimensions.
            #
            # This ensures all downstream images have the exact
            # same canvas size.
            # --------------------------------------------------------------

            if image.size != (
                int(width),
                int(height),
            ):

                image = image.resize(
                    (
                        int(width),
                        int(height),
                    ),
                    Image.Resampling.LANCZOS,
                )

            image.save(
                path,
                format="PNG",
                optimize=True,
            )

        except Exception as error:

            raise RuntimeError(
                f"Failed to normalize image to PNG: "
                f"{error}"
            )

    else:

        # ------------------------------------------------------------------
        # Fallback when Pillow is unavailable.
        # ------------------------------------------------------------------

        with open(
            path,
            "wb",
        ) as file:

            file.write(
                content
            )

    # ----------------------------------------------------------------------
    # Final filesystem validation.
    # ----------------------------------------------------------------------

    if not os.path.exists(
        path
    ):

        raise RuntimeError(
            f"Image was not created: {path}"
        )

    size = os.path.getsize(
        path
    )

    if size < MIN_IMAGE_BYTES:

        try:

            os.remove(
                path
            )

        except Exception:

            pass

        raise RuntimeError(
            f"Generated image appears invalid: "
            f"{path}"
        )

    # ----------------------------------------------------------------------
    # Final PNG validation.
    # ----------------------------------------------------------------------

    if Image is not None:

        try:

            with Image.open(
                path
            ) as image:

                if image.format != EXPECTED_FORMAT:

                    raise RuntimeError(
                        f"Expected PNG but got "
                        f"{image.format}."
                    )

                if image.size != (
                    int(width),
                    int(height),
                ):

                    raise RuntimeError(
                        "Final image dimensions are incorrect: "
                        f"{image.size} instead of "
                        f"{width}x{height}."
                    )

                image.verify()

        except Exception as error:

            raise RuntimeError(
                f"Final PNG validation failed: "
                f"{error}"
            )

    return path


# ==========================================================================
# IMAGE CONFIG
# ==========================================================================

def _get_image_dimensions(
    config,
):
    """
    Read image dimensions from config.yaml.

    Portrait orientation is always enforced.
    """

    image_config = (
        config.get(
            "image",
            {},
        )
        if isinstance(
            config,
            dict,
        )
        else {}
    )

    if not isinstance(
        image_config,
        dict,
    ):

        image_config = {}

    width = _safe_int(
        image_config.get(
            "width",
            DEFAULT_WIDTH,
        ),
        DEFAULT_WIDTH,
    )

    height = _safe_int(
        image_config.get(
            "height",
            DEFAULT_HEIGHT,
        ),
        DEFAULT_HEIGHT,
    )

    if width <= 0:
        width = DEFAULT_WIDTH

    if height <= 0:
        height = DEFAULT_HEIGHT

    # ----------------------------------------------------------------------
    # Force portrait.
    # ----------------------------------------------------------------------

    if width >= height:

        width, height = (
            height,
            width,
        )

    return width, height


# ==========================================================================
# SCRIPT STRUCTURE VALIDATION
# ==========================================================================

def _validate_script_structure(
    script,
):
    """
    Validate the production contract before any image generation begins.
    """

    if not isinstance(
        script,
        dict,
    ):

        raise RuntimeError(
            "Script must be a dictionary."
        )

    scenes = script.get(
        "scene_plan",
        [],
    )

    if not isinstance(
        scenes,
        list,
    ):

        raise RuntimeError(
            "script.scene_plan must be a list."
        )

    if len(
        scenes
    ) != EXPECTED_SCENES:

        raise RuntimeError(
            f"Expected exactly "
            f"{EXPECTED_SCENES} scenes, "
            f"but found {len(scenes)}."
        )

    total_visuals = 0

    for scene_index, scene in enumerate(
        scenes,
        start=1,
    ):

        if not isinstance(
            scene,
            dict,
        ):

            raise RuntimeError(
                f"Scene {scene_index} "
                "is not an object."
            )

        scene_number = _safe_int(
            scene.get(
                "scene",
                scene_index,
            ),
            scene_index,
        )

        if scene_number != scene_index:

            raise RuntimeError(
                f"Scene {scene_index} has invalid "
                f"scene number: {scene_number}."
            )

        visuals = scene.get(
            "visuals",
            [],
        )

        if not isinstance(
            visuals,
            list,
        ):

            raise RuntimeError(
                f"Scene {scene_index} "
                "visuals must be a list."
            )

        if len(
            visuals
        ) != VISUALS_PER_SCENE:

            raise RuntimeError(
                f"Scene {scene_index} must contain "
                f"exactly {VISUALS_PER_SCENE} visuals, "
                f"but found {len(visuals)}."
            )

        for visual_index, visual in enumerate(
            visuals,
            start=1,
        ):

            if not isinstance(
                visual,
                dict,
            ):

                raise RuntimeError(
                    f"Scene {scene_index} "
                    f"visual {visual_index} "
                    "is invalid."
                )

            prompt = _clean_prompt(
                visual.get(
                    "image_prompt",
                    "",
                )
            )

            if not prompt:

                raise RuntimeError(
                    f"Scene {scene_index} "
                    f"visual {visual_index} "
                    "has an empty image_prompt."
                )

            total_visuals += 1

    if total_visuals != EXPECTED_TOTAL_IMAGES:

        raise RuntimeError(
            f"Expected exactly "
            f"{EXPECTED_TOTAL_IMAGES} visuals, "
            f"but found {total_visuals}."
        )

    return scenes


# ==========================================================================
# CONTINUITY VALIDATION
# ==========================================================================

def _validate_continuity_metadata(
    script,
):
    """
    Validate the visual continuity package.

    Continuity is strongly recommended but the script can still
    function for stories that do not have recurring characters.
    """

    identity = _get_visual_identity(
        script
    )

    continuity = _get_visual_continuity(
        script
    )

    print(
        "Visual identity:"
    )

    print(
        f"  Style: "
        f"{identity['style'] or 'not specified'}"
    )

    print(
        f"  Palette: "
        f"{identity['palette'] or 'not specified'}"
    )

    print(
        f"  Mood: "
        f"{identity['mood_arc'] or 'not specified'}"
    )

    print(
        "Visual continuity:"
    )

    print(
        f"  Recurring subjects: "
        f"{len(continuity['subjects'])}"
    )

    print(
        f"  Recurring objects: "
        f"{len(continuity['objects'])}"
    )

    print(
        f"  Environment: "
        f"{'yes' if continuity['environment'] else 'no'}"
    )

    print(
        f"  Continuity rules: "
        f"{len(continuity['rules'])}"
    )

    return True


# ==========================================================================
# GENERATE ALL VISUALS
# ==========================================================================

def generate_images(
    script,
    workdir,
    config,
):
    """
    Generate exactly 14 AI images.

    Return format:

    [
        [
            scene_01_shot_01.png,
            scene_01_shot_02.png
        ],
        [
            scene_02_shot_01.png,
            scene_02_shot_02.png
        ],
        ...
    ]

    This structure is intentionally preserved for assemble.py.
    """

    os.makedirs(
        workdir,
        exist_ok=True,
    )

    # ----------------------------------------------------------------------
    # Validate script BEFORE contacting image provider.
    # ----------------------------------------------------------------------

    scenes = _validate_script_structure(
        script
    )

    _validate_continuity_metadata(
        script
    )

    # ----------------------------------------------------------------------
    # Dimensions
    # ----------------------------------------------------------------------

    width, height = _get_image_dimensions(
        config
    )

    # ----------------------------------------------------------------------
    # Seed
    # ----------------------------------------------------------------------

    base_seed = _get_base_seed(
        script
    )

    image_paths = []

    print("=" * 80)
    print("🎨 GENERATING AI VISUALS")
    print("=" * 80)

    print(
        f"Scenes: "
        f"{len(scenes)}"
    )

    print(
        f"Visuals per scene: "
        f"{VISUALS_PER_SCENE}"
    )

    print(
        f"Total images: "
        f"{EXPECTED_TOTAL_IMAGES}"
    )

    print(
        f"Resolution: "
        f"{width}x{height}"
    )

    print(
        f"Base seed: "
        f"{base_seed}"
    )

    print(
        f"Provider: "
        f"Pollinations AI"
    )

    print(
        f"Model: "
        f"{MODEL_NAME}"
    )

    print(
        "Continuity system: ENABLED"
    )

    print(
        "Portrait normalization: ENABLED"
    )

    print(
        "PNG validation: ENABLED"
    )

    print("=" * 80)

    # ----------------------------------------------------------------------
    # Scene generation
    # ----------------------------------------------------------------------

    for scene_index, scene in enumerate(
        scenes,
        start=1,
    ):

        visuals = scene[
            "visuals"
        ]

        scene_paths = []

        print("=" * 80)
        print(
            f"🎬 SCENE "
            f"{scene_index}/{EXPECTED_SCENES}"
        )
        print("=" * 80)

        # ------------------------------------------------------------------
        # Two shots per scene
        # ------------------------------------------------------------------

        for visual_index, visual in enumerate(
            visuals,
            start=1,
        ):

            prompt = build_prompt(
                scene,
                visual,
                script,
                scene_index,
                visual_index,
            )

            shot_seed = _get_shot_seed(
                base_seed,
                scene_index,
                visual_index,
            )

            print("=" * 80)

            print(
                f"🖼️ SHOT "
                f"{visual_index}/{VISUALS_PER_SCENE}"
            )

            print(
                f"Scene: "
                f"{scene_index}"
            )

            print(
                f"Seed: "
                f"{shot_seed}"
            )

            print(
                f"Style: "
                f"{visual.get('image_style', '')}"
            )

            print(
                f"Visual impact: "
                f"{visual.get('visual_impact', '')}"
            )

            print(
                f"Prompt: "
                f"{prompt}"
            )

            print("=" * 80)

            # --------------------------------------------------------------
            # Generate
            # --------------------------------------------------------------

            image = generate_image(
                prompt,
                width,
                height,
                shot_seed,
            )

            # --------------------------------------------------------------
            # Save
            # --------------------------------------------------------------

            filename = os.path.join(
                workdir,
                (
                    f"scene_{scene_index:02d}"
                    f"_shot_{visual_index:02d}.png"
                ),
            )

            _save_image(
                image,
                filename,
                width,
                height,
            )

            scene_paths.append(
                filename
            )

            print(
                f"✅ Saved: "
                f"{filename}"
            )

            # --------------------------------------------------------------
            # Prevent burst requests.
            # --------------------------------------------------------------

            if not (
                scene_index == EXPECTED_SCENES
                and
                visual_index == VISUALS_PER_SCENE
            ):

                time.sleep(
                    BETWEEN_IMAGE_DELAY
                )

        image_paths.append(
            scene_paths
        )

    # ==========================================================================
    # FINAL VALIDATION
    # ==========================================================================

    total_images = sum(
        len(scene_paths)
        for scene_paths in image_paths
    )

    if total_images != EXPECTED_TOTAL_IMAGES:

        raise RuntimeError(
            f"Expected exactly "
            f"{EXPECTED_TOTAL_IMAGES} generated images, "
            f"but generated "
            f"{total_images}."
        )

    # ----------------------------------------------------------------------
    # Verify every scene.
    # ----------------------------------------------------------------------

    for scene_index, scene_paths in enumerate(
        image_paths,
        start=1,
    ):

        if len(
            scene_paths
        ) != VISUALS_PER_SCENE:

            raise RuntimeError(
                f"Scene {scene_index} "
                f"contains {len(scene_paths)} "
                f"images instead of "
                f"{VISUALS_PER_SCENE}."
            )

        for visual_index, path in enumerate(
            scene_paths,
            start=1,
        ):

            if not os.path.exists(
                path
            ):

                raise RuntimeError(
                    f"Missing generated image: "
                    f"Scene {scene_index}, "
                    f"Shot {visual_index}: "
                    f"{path}"
                )

            if os.path.getsize(
                path
            ) < MIN_IMAGE_BYTES:

                raise RuntimeError(
                    f"Generated image is too small: "
                    f"{path}"
                )

            # --------------------------------------------------------------
            # Final image validation.
            # --------------------------------------------------------------

            if Image is not None:

                try:

                    with Image.open(
                        path
                    ) as image:

                        if image.format != EXPECTED_FORMAT:

                            raise RuntimeError(
                                f"Scene {scene_index} "
                                f"Shot {visual_index}: "
                                f"expected PNG, got "
                                f"{image.format}."
                            )

                        if image.size != (
                            width,
                            height,
                        ):

                            raise RuntimeError(
                                f"Scene {scene_index} "
                                f"Shot {visual_index}: "
                                f"expected "
                                f"{width}x{height}, "
                                f"got "
                                f"{image.size}."
                            )

                        image.verify()

                except Exception as error:

                    raise RuntimeError(
                        f"Final image validation failed "
                        f"for Scene {scene_index}, "
                        f"Shot {visual_index}: "
                        f"{error}"
                    )

    # ==========================================================================
    # SUMMARY
    # ==========================================================================

    print("=" * 80)
    print("✅ VISUAL GENERATION COMPLETE")
    print("=" * 80)

    print(
        f"Scenes: "
        f"{len(image_paths)}"
    )

    print(
        f"Images generated: "
        f"{total_images}"
    )

    print(
        f"Expected images: "
        f"{EXPECTED_TOTAL_IMAGES}"
    )

    print(
        f"Resolution: "
        f"{width}x{height}"
    )

    print(
        "Visual continuity: ENABLED"
    )

    print(
        "Style lock: APPLIED"
    )

    print(
        "Recurring subjects: APPLIED"
    )

    print(
        "Environment continuity: APPLIED"
    )

    print(
        "PNG normalization: COMPLETE"
    )

    print(
        "Image validation: PASSED"
    )

    print("=" * 80)

    return image_paths


# ==========================================================================
# OPTIONAL SINGLE IMAGE HELPER
# ==========================================================================

def generate_single_image(
    prompt,
    workdir,
    filename="generated.png",
    width=DEFAULT_WIDTH,
    height=DEFAULT_HEIGHT,
    seed=None,
):
    """
    Generate one standalone image.

    This helper remains compatible with any existing scripts
    that use it independently from the main pipeline.
    """

    os.makedirs(
        workdir,
        exist_ok=True,
    )

    if seed is None:

        seed = int(
            time.time()
        )

    prompt = _clean_prompt(
        prompt
    )

    if not prompt:

        raise RuntimeError(
            "Cannot generate image "
            "with an empty prompt."
        )

    # ----------------------------------------------------------------------
    # Force portrait.
    # ----------------------------------------------------------------------

    if width >= height:

        width, height = (
            height,
            width,
        )

    image = generate_image(
        prompt,
        width,
        height,
        int(seed),
    )

    path = os.path.join(
        workdir,
        filename,
    )

    _save_image(
        image,
        path,
        width,
        height,
    )

    return path