"""
generate_images.py

AI Visual Generation for Mint-YT-Factory
Version 7.1

Purpose:
Generate AI visuals from the storyboard produced by generate_script.py.

Architecture:

generate_script.py
        ↓
Short semantic image_prompt
        ↓
Pollinations AI
        ↓
PNG image
        ↓
assemble.py

Important:
- Gemini controls the visual description.
- Pollinations receives the image_prompt directly.
- No additional creative or technical prompt instructions are added.
- Exactly 2 visuals per scene.
- Exactly 14 images per Short.
- Controlled seed variation.
- Automatic retries.
- Compatible with the existing main.py pipeline.
"""

import os
import time
import urllib.parse
import requests


# ==========================================================================
# CONFIGURATION
# ==========================================================================

BASE_URL = "https://image.pollinations.ai/prompt/"

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

MAX_RETRIES = 5
RETRY_DELAY = 5

DEFAULT_WIDTH = 768
DEFAULT_HEIGHT = 1365

VISUALS_PER_SCENE = 2
EXPECTED_TOTAL_IMAGES = 14


# ==========================================================================
# PROMPT CLEANING
# ==========================================================================

def _clean_prompt(text):
    """
    Clean accidental formatting without changing
    the visual meaning generated by Gemini.
    """

    if not text:
        return ""

    text = str(text)

    text = text.replace(
        "\n",
        " ",
    )

    text = text.replace(
        "```",
        "",
    )

    text = " ".join(
        text.split()
    )

    return text.strip()


# ==========================================================================
# BUILD PROMPT
# ==========================================================================

def build_prompt(
    scene,
    visual,
    script=None,
):
    """
    Use Gemini's image_prompt directly.

    No additional creative or technical instructions
    are added here.

    Gemini is responsible for the complete semantic
    visual description.
    """

    prompt = _clean_prompt(
        visual.get(
            "image_prompt",
            "",
        )
    )

    if not prompt:

        raise RuntimeError(
            "Visual contains an empty image_prompt."
        )

    return prompt


# ==========================================================================
# SEED
# ==========================================================================

def _get_base_seed(script):

    try:

        seed = int(
            script.get(
                "image_generation",
                {},
            ).get(
                "seed",
                int(time.time()),
            )
        )

    except Exception:

        seed = int(time.time())

    return seed


# ==========================================================================
# IMAGE REQUEST
# ==========================================================================

def generate_image(
    prompt,
    width,
    height,
    seed,
):
    """
    Generate one image through Pollinations.

    The Gemini prompt is sent directly without
    adding creative or technical instructions.
    """

    full_prompt = _clean_prompt(
        prompt
    )

    if not full_prompt:

        raise RuntimeError(
            "Cannot generate image with an empty prompt."
        )

    encoded_prompt = urllib.parse.quote(
        full_prompt,
        safe="",
    )

    url = (
        BASE_URL
        + encoded_prompt
        + "?model=flux"
        + f"&width={int(width)}"
        + f"&height={int(height)}"
        + f"&seed={int(seed)}"
        + "&enhance=true"
        + "&nologo=true"
    )

    print("=" * 80)
    print("IMAGE GENERATION REQUEST")
    print("=" * 80)

    print(
        f"Seed: {seed}"
    )

    print(
        f"Size: {width}x{height}"
    )

    print(
        f"Prompt length: {len(full_prompt)}"
    )

    print(
        f"Prompt: {full_prompt}"
    )

    print("=" * 80)

    last_error = None

    for attempt in range(
        1,
        MAX_RETRIES + 1,
    ):

        try:

            print(
                f"🎨 Image attempt "
                f"{attempt}/{MAX_RETRIES}"
            )

            response = requests.get(
                url,
                headers=HEADERS,
                timeout=180,
            )

            print(
                f"HTTP status: "
                f"{response.status_code}"
            )

            response.raise_for_status()

            content = response.content

            if not content:

                raise RuntimeError(
                    "Image response was empty."
                )

            content_type = (
                response.headers.get(
                    "Content-Type",
                    "",
                ).lower()
            )

            if (
                "image" not in content_type
                and len(content) < 10000
            ):

                raise RuntimeError(
                    "Server returned an unexpected "
                    "non-image response."
                )

            print(
                "✅ Image generated successfully."
            )

            return content

        except Exception as error:

            last_error = error

            print(
                f"❌ Image attempt "
                f"{attempt} failed:"
            )

            print(
                error
            )

            if attempt < MAX_RETRIES:

                print(
                    f"⏳ Retrying in "
                    f"{RETRY_DELAY} seconds..."
                )

                time.sleep(
                    RETRY_DELAY
                )

    raise RuntimeError(
        "Failed to generate image after "
        f"{MAX_RETRIES} attempts: "
        f"{last_error}"
    )


# ==========================================================================
# SAVE IMAGE
# ==========================================================================

def _save_image(
    content,
    path,
):

    with open(
        path,
        "wb",
    ) as file:

        file.write(
            content
        )

    size = os.path.getsize(
        path
    )

    if size < 1000:

        raise RuntimeError(
            f"Generated image appears invalid: "
            f"{path}"
        )

    return path


# ==========================================================================
# GENERATE ALL VISUALS
# ==========================================================================

def generate_images(
    script,
    workdir,
    config,
):

    os.makedirs(
        workdir,
        exist_ok=True,
    )

    image_config = config.get(
        "image",
        {},
    )

    width = int(
        image_config.get(
            "width",
            DEFAULT_WIDTH,
        )
    )

    height = int(
        image_config.get(
            "height",
            DEFAULT_HEIGHT,
        )
    )

    # Force portrait orientation.
    if width >= height:

        width, height = (
            height,
            width,
        )

    base_seed = _get_base_seed(
        script
    )

    image_paths = []

    scenes = script.get(
        "scene_plan",
        [],
    )

    if not scenes:

        raise RuntimeError(
            "Script contains no scene_plan."
        )

    # ----------------------------------------------------------------------
    # VALIDATE SCENE COUNT
    # ----------------------------------------------------------------------

    expected_scene_count = 7

    if len(scenes) != expected_scene_count:

        raise RuntimeError(
            f"Expected exactly "
            f"{expected_scene_count} scenes, "
            f"but found {len(scenes)}."
        )

    # ----------------------------------------------------------------------
    # VALIDATE TOTAL VISUAL COUNT
    # ----------------------------------------------------------------------

    total_expected = (
        len(scenes)
        * VISUALS_PER_SCENE
    )

    if total_expected != EXPECTED_TOTAL_IMAGES:

        raise RuntimeError(
            f"Pipeline configuration error: "
            f"expected {EXPECTED_TOTAL_IMAGES} images "
            f"but calculated {total_expected}."
        )

    print("=" * 80)
    print("🎨 GENERATING AI VISUALS")
    print("=" * 80)

    print(
        f"Scenes: {len(scenes)}"
    )

    print(
        f"Visuals per scene: "
        f"{VISUALS_PER_SCENE}"
    )

    print(
        f"Total images: "
        f"{EXPECTED_TOTAL_IMAGES}"
    )

    print(
        f"Resolution: {width}x{height}"
    )

    print(
        f"Base seed: {base_seed}"
    )

    print(
        "Prompt mode: DIRECT GEMINI IMAGE PROMPTS"
    )

    print("=" * 80)

    # ----------------------------------------------------------------------
    # EVERY SCENE
    # ----------------------------------------------------------------------

    for scene_index, scene in enumerate(
        scenes,
        start=1,
    ):

        visuals = scene.get(
            "visuals",
            [],
        )

        if not isinstance(
            visuals,
            list,
        ):

            raise RuntimeError(
                f"Scene {scene_index} visuals "
                "must be a list."
            )

        # STRICTLY REQUIRE 2 VISUALS.
        if len(visuals) != VISUALS_PER_SCENE:

            raise RuntimeError(
                f"Scene {scene_index} must contain "
                f"exactly {VISUALS_PER_SCENE} visuals, "
                f"but found {len(visuals)}."
            )

        scene_paths = []

        print("=" * 80)

        print(
            f"SCENE {scene_index}/{len(scenes)}"
        )

        print(
            f"Visuals: {len(visuals)}"
        )

        print("=" * 80)

        # ------------------------------------------------------------------
        # EVERY SHOT
        # ------------------------------------------------------------------

        for visual_index, visual in enumerate(
            visuals,
            start=1,
        ):

            if not isinstance(
                visual,
                dict,
            ):

                raise RuntimeError(
                    f"Scene {scene_index} visual "
                    f"{visual_index} is invalid."
                )

            prompt = build_prompt(
                scene,
                visual,
                script,
            )

            # Deterministic but different seed for every shot.
            shot_seed = (
                base_seed
                + (
                    scene_index * 100
                )
                + visual_index
            )

            print(
                f"SHOT {visual_index}/{len(visuals)}"
            )

            print(
                f"Seed: {shot_seed}"
            )

            print(
                f"Prompt: {prompt}"
            )

            print("=" * 80)

            image = generate_image(
                prompt,
                width,
                height,
                shot_seed,
            )

            filename = os.path.join(
                workdir,
                (
                    f"scene_{scene_index:02d}"
                    f"_shot_{visual_index:02d}.png"
                ),
            )

            _save_image(
                image,
                filename,
            )

            print(
                f"✅ Saved -> {filename}"
            )

            scene_paths.append(
                filename
            )

            # Small delay to reduce request bursts.
            time.sleep(2)

        image_paths.append(
            scene_paths
        )

    # ----------------------------------------------------------------------
    # FINAL VALIDATION
    # ----------------------------------------------------------------------

    total_images = sum(
        len(scene)
        for scene in image_paths
    )

    if total_images != EXPECTED_TOTAL_IMAGES:

        raise RuntimeError(
            f"Expected exactly "
            f"{EXPECTED_TOTAL_IMAGES} generated images, "
            f"but generated {total_images}."
        )

    # ----------------------------------------------------------------------
    # SUMMARY
    # ----------------------------------------------------------------------

    print("=" * 80)
    print("✅ VISUAL GENERATION COMPLETE")
    print("=" * 80)

    print(
        f"Scenes: {len(image_paths)}"
    )

    print(
        f"Images generated: {total_images}"
    )

    print(
        f"Expected images: "
        f"{EXPECTED_TOTAL_IMAGES}"
    )

    print("=" * 80)

    return image_paths


# ==========================================================================
# OPTIONAL SINGLE-IMAGE HELPER
# ==========================================================================

def generate_single_image(
    prompt,
    workdir,
    filename="generated.png",
    width=DEFAULT_WIDTH,
    height=DEFAULT_HEIGHT,
    seed=None,
):

    os.makedirs(
        workdir,
        exist_ok=True,
    )

    if seed is None:

        seed = int(
            time.time()
        )

    image = generate_image(
        prompt,
        width,
        height,
        seed,
    )

    path = os.path.join(
        workdir,
        filename,
    )

    _save_image(
        image,
        path,
    )

    return path