"""
generate_images.py
Mint-YT-Factory

Version 7.2

AI Visual Generation

Pipeline:

generate_script.py
        ↓
Gemini semantic image prompts
        ↓
Pollinations AI
        ↓
14 PNG visuals
        ↓
assemble.py

Features:
- Exactly 7 scenes
- Exactly 2 visuals per scene
- Exactly 14 images
- Controlled deterministic seeds
- Automatic retries
- Image-response validation
- Portrait resolution
- Scene-grouped output
- Compatible with main.py
- Compatible with assemble.py
"""

import os
import time
import urllib.parse
import requests


# ==========================================================================
# CONFIGURATION
# ==========================================================================

BASE_URL = "https://image.pollinations.ai/prompt/"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 "
        "(Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 "
        "(KHTML, like Gecko) "
        "Chrome/140.0 Safari/537.36"
    ),
    "Accept": "image/png,image/jpeg,image/webp,*/*",
}

MAX_RETRIES = 5
RETRY_DELAY = 5

DEFAULT_WIDTH = 768
DEFAULT_HEIGHT = 1365

VISUALS_PER_SCENE = 2
EXPECTED_SCENES = 7
EXPECTED_TOTAL_IMAGES = 14

MIN_IMAGE_BYTES = 10_000

REQUEST_TIMEOUT = 180

BETWEEN_IMAGE_DELAY = 2


# ==========================================================================
# PROMPT CLEANING
# ==========================================================================

def _clean_prompt(text):
    """
    Clean accidental formatting while preserving
    the semantic visual prompt generated by Gemini.
    """

    if not text:
        return ""

    text = str(text)

    text = text.replace(
        "\n",
        " ",
    )

    text = text.replace(
        "```",
        "",
    )

    text = " ".join(
        text.split()
    )

    return text.strip()


# ==========================================================================
# BUILD PROMPT
# ==========================================================================

def build_prompt(
    scene,
    visual,
    script=None,
):
    """
    Use Gemini's semantic image prompt directly.

    We intentionally do NOT add:
    - camera instructions
    - aspect ratio instructions
    - rendering instructions
    - negative prompts
    - AI instructions
    - YouTube instructions

    Gemini is responsible for the visual description.
    """

    prompt = _clean_prompt(
        visual.get(
            "image_prompt",
            "",
        )
    )

    if not prompt:

        raise RuntimeError(
            "Visual contains an empty image_prompt."
        )

    return prompt


# ==========================================================================
# SEED MANAGEMENT
# ==========================================================================

def _get_base_seed(script):
    """
    Get the deterministic seed generated by generate_script.py.
    """

    try:

        seed = int(
            script.get(
                "image_generation",
                {},
            ).get(
                "seed",
                int(time.time()),
            )
        )

    except Exception:

        seed = int(time.time())

    return seed


def _get_shot_seed(
    base_seed,
    scene_index,
    visual_index,
):
    """
    Generate a unique but deterministic seed
    for every visual.
    """

    return (
        base_seed
        + (scene_index * 100)
        + visual_index
    )


# ==========================================================================
# IMAGE URL
# ==========================================================================

def _build_image_url(
    prompt,
    width,
    height,
    seed,
):
    """
    Build the Pollinations image URL.
    """

    encoded_prompt = urllib.parse.quote(
        prompt,
        safe="",
    )

    url = (
        BASE_URL
        + encoded_prompt
        + "?model=flux"
        + f"&width={int(width)}"
        + f"&height={int(height)}"
        + f"&seed={int(seed)}"
        + "&enhance=true"
        + "&nologo=true"
    )

    return url


# ==========================================================================
# RESPONSE VALIDATION
# ==========================================================================

def _validate_image_response(
    response,
):
    """
    Validate that Pollinations returned
    an actual image rather than an HTML/JSON
    error response.
    """

    if response is None:

        raise RuntimeError(
            "Empty HTTP response."
        )

    if response.status_code != 200:

        raise RuntimeError(
            f"HTTP {response.status_code}"
        )

    content = response.content

    if not content:

        raise RuntimeError(
            "Image response was empty."
        )

    content_type = (
        response.headers.get(
            "Content-Type",
            "",
        )
        .lower()
    )

    # ------------------------------------------------------
    # Preferred validation
    # ------------------------------------------------------

    if "image" in content_type:

        if len(content) < MIN_IMAGE_BYTES:

            raise RuntimeError(
                "Image response is suspiciously small."
            )

        return content

    # ------------------------------------------------------
    # Fallback validation
    #
    # Some image endpoints may not return a
    # perfect Content-Type header.
    # ------------------------------------------------------

    image_signatures = (
        b"\x89PNG",
        b"\xff\xd8\xff",
        b"RIFF",
    )

    if any(
        content.startswith(signature)
        for signature in image_signatures
    ):

        if len(content) < MIN_IMAGE_BYTES:

            raise RuntimeError(
                "Image response is suspiciously small."
            )

        return content

    # ------------------------------------------------------
    # Not an image
    # ------------------------------------------------------

    preview = content[:300]

    try:

        preview = preview.decode(
            "utf-8",
            errors="ignore",
        )

    except Exception:

        preview = "<binary response>"

    raise RuntimeError(
        "Server returned a non-image response: "
        f"{preview}"
    )


# ==========================================================================
# IMAGE REQUEST
# ==========================================================================

def generate_image(
    prompt,
    width,
    height,
    seed,
):
    """
    Generate one image through Pollinations.
    """

    prompt = _clean_prompt(
        prompt
    )

    if not prompt:

        raise RuntimeError(
            "Cannot generate an image "
            "with an empty prompt."
        )

    url = _build_image_url(
        prompt,
        width,
        height,
        seed,
    )

    print("=" * 80)
    print("IMAGE GENERATION REQUEST")
    print("=" * 80)

    print(
        f"Seed: {seed}"
    )

    print(
        f"Size: {width}x{height}"
    )

    print(
        f"Prompt length: {len(prompt)}"
    )

    print(
        f"Prompt: {prompt}"
    )

    print("=" * 80)

    last_error = None

    session = requests.Session()

    session.headers.update(
        HEADERS
    )

    try:

        for attempt in range(
            1,
            MAX_RETRIES + 1,
        ):

            try:

                print(
                    f"🎨 Image attempt "
                    f"{attempt}/{MAX_RETRIES}"
                )

                response = session.get(
                    url,
                    timeout=REQUEST_TIMEOUT,
                )

                print(
                    f"HTTP status: "
                    f"{response.status_code}"
                )

                content = _validate_image_response(
                    response
                )

                print(
                    f"Image bytes: "
                    f"{len(content):,}"
                )

                print(
                    "✅ Image generated successfully."
                )

                return content

            except Exception as error:

                last_error = error

                print(
                    f"❌ Image attempt "
                    f"{attempt} failed:"
                )

                print(
                    str(error)
                )

                if attempt < MAX_RETRIES:

                    print(
                        f"⏳ Retrying in "
                        f"{RETRY_DELAY} seconds..."
                    )

                    time.sleep(
                        RETRY_DELAY
                    )

    finally:

        session.close()

    raise RuntimeError(
        "Failed to generate image after "
        f"{MAX_RETRIES} attempts: "
        f"{last_error}"
    )


# ==========================================================================
# SAVE IMAGE
# ==========================================================================

def _save_image(
    content,
    path,
):
    """
    Save and validate generated image.
    """

    if not content:

        raise RuntimeError(
            "Cannot save empty image content."
        )

    output_dir = os.path.dirname(
        path
    )

    if output_dir:

        os.makedirs(
            output_dir,
            exist_ok=True,
        )

    with open(
        path,
        "wb",
    ) as file:

        file.write(
            content
        )

    size = os.path.getsize(
        path
    )

    if size < MIN_IMAGE_BYTES:

        try:

            os.remove(
                path
            )

        except Exception:

            pass

        raise RuntimeError(
            f"Generated image appears invalid: "
            f"{path}"
        )

    return path


# ==========================================================================
# IMAGE CONFIG
# ==========================================================================

def _get_image_dimensions(
    config,
):
    """
    Read image dimensions from config.yaml.

    Forces portrait orientation.
    """

    image_config = (
        config.get(
            "image",
            {},
        )
        if isinstance(
            config,
            dict,
        )
        else {}
    )

    if not isinstance(
        image_config,
        dict,
    ):

        image_config = {}

    try:

        width = int(
            image_config.get(
                "width",
                DEFAULT_WIDTH,
            )
        )

    except Exception:

        width = DEFAULT_WIDTH

    try:

        height = int(
            image_config.get(
                "height",
                DEFAULT_HEIGHT,
            )
        )

    except Exception:

        height = DEFAULT_HEIGHT

    # ------------------------------------------------------
    # Force portrait
    # ------------------------------------------------------

    if width >= height:

        width, height = (
            height,
            width,
        )

    return width, height


# ==========================================================================
# VALIDATE SCRIPT
# ==========================================================================

def _validate_script_structure(
    script,
):
    """
    Make sure the storyboard matches
    the production contract.
    """

    scenes = script.get(
        "scene_plan",
        [],
    )

    if not isinstance(
        scenes,
        list,
    ):

        raise RuntimeError(
            "script.scene_plan must be a list."
        )

    if len(scenes) != EXPECTED_SCENES:

        raise RuntimeError(
            f"Expected exactly "
            f"{EXPECTED_SCENES} scenes, "
            f"but found {len(scenes)}."
        )

    for scene_index, scene in enumerate(
        scenes,
        start=1,
    ):

        if not isinstance(
            scene,
            dict,
        ):

            raise RuntimeError(
                f"Scene {scene_index} "
                "is not an object."
            )

        visuals = scene.get(
            "visuals",
            [],
        )

        if not isinstance(
            visuals,
            list,
        ):

            raise RuntimeError(
                f"Scene {scene_index} "
                "visuals must be a list."
            )

        if len(visuals) != VISUALS_PER_SCENE:

            raise RuntimeError(
                f"Scene {scene_index} must contain "
                f"exactly {VISUALS_PER_SCENE} visuals, "
                f"but found {len(visuals)}."
            )

        for visual_index, visual in enumerate(
            visuals,
            start=1,
        ):

            if not isinstance(
                visual,
                dict,
            ):

                raise RuntimeError(
                    f"Scene {scene_index} "
                    f"visual {visual_index} "
                    "is invalid."
                )

            prompt = _clean_prompt(
                visual.get(
                    "image_prompt",
                    "",
                )
            )

            if not prompt:

                raise RuntimeError(
                    f"Scene {scene_index} "
                    f"visual {visual_index} "
                    "has an empty image_prompt."
                )

    return scenes


# ==========================================================================
# GENERATE ALL VISUALS
# ==========================================================================

def generate_images(
    script,
    workdir,
    config,
):
    """
    Generate exactly 14 images.

    Return format:

    [
        [
            scene_01_shot_01.png,
            scene_01_shot_02.png
        ],
        [
            scene_02_shot_01.png,
            scene_02_shot_02.png
        ],
        ...
    ]

    This structure is required by assemble.py.
    """

    os.makedirs(
        workdir,
        exist_ok=True,
    )

    width, height = _get_image_dimensions(
        config
    )

    scenes = _validate_script_structure(
        script
    )

    base_seed = _get_base_seed(
        script
    )

    image_paths = []

    print("=" * 80)
    print("🎨 GENERATING AI VISUALS")
    print("=" * 80)

    print(
        f"Scenes: {len(scenes)}"
    )

    print(
        f"Visuals per scene: "
        f"{VISUALS_PER_SCENE}"
    )

    print(
        f"Total images: "
        f"{EXPECTED_TOTAL_IMAGES}"
    )

    print(
        f"Resolution: "
        f"{width}x{height}"
    )

    print(
        f"Base seed: "
        f"{base_seed}"
    )

    print(
        "Provider: Pollinations AI"
    )

    print(
        "Prompt mode: "
        "DIRECT GEMINI SEMANTIC PROMPTS"
    )

    print("=" * 80)

    # ----------------------------------------------------------------------
    # SCENES
    # ----------------------------------------------------------------------

    for scene_index, scene in enumerate(
        scenes,
        start=1,
    ):

        visuals = scene[
            "visuals"
        ]

        scene_paths = []

        print("=" * 80)
        print(
            f"🎬 SCENE "
            f"{scene_index}/{EXPECTED_SCENES}"
        )
        print("=" * 80)

        # ------------------------------------------------------------------
        # SHOTS
        # ------------------------------------------------------------------

        for visual_index, visual in enumerate(
            visuals,
            start=1,
        ):

            prompt = build_prompt(
                scene,
                visual,
                script,
            )

            shot_seed = _get_shot_seed(
                base_seed,
                scene_index,
                visual_index,
            )

            print("=" * 80)

            print(
                f"🖼️ SHOT "
                f"{visual_index}/{VISUALS_PER_SCENE}"
            )

            print(
                f"Scene: "
                f"{scene_index}"
            )

            print(
                f"Seed: "
                f"{shot_seed}"
            )

            print(
                f"Style: "
                f"{visual.get('image_style', '')}"
            )

            print(
                f"Visual impact: "
                f"{visual.get('visual_impact', '')}"
            )

            print(
                f"Prompt: "
                f"{prompt}"
            )

            print("=" * 80)

            image = generate_image(
                prompt,
                width,
                height,
                shot_seed,
            )

            filename = os.path.join(
                workdir,
                (
                    f"scene_{scene_index:02d}"
                    f"_shot_{visual_index:02d}.png"
                ),
            )

            _save_image(
                image,
                filename,
            )

            scene_paths.append(
                filename
            )

            print(
                f"✅ Saved: "
                f"{filename}"
            )

            # --------------------------------------------------------------
            # Prevent burst requests.
            # --------------------------------------------------------------

            if not (
                scene_index == EXPECTED_SCENES
                and visual_index == VISUALS_PER_SCENE
            ):

                time.sleep(
                    BETWEEN_IMAGE_DELAY
                )

        image_paths.append(
            scene_paths
        )

    # ==========================================================================
    # FINAL VALIDATION
    # ==========================================================================

    total_images = sum(
        len(scene)
        for scene in image_paths
    )

    if total_images != EXPECTED_TOTAL_IMAGES:

        raise RuntimeError(
            f"Expected exactly "
            f"{EXPECTED_TOTAL_IMAGES} generated images, "
            f"but generated "
            f"{total_images}."
        )

    # ----------------------------------------------------------------------
    # Verify every file exists.
    # ----------------------------------------------------------------------

    for scene_index, scene_paths in enumerate(
        image_paths,
        start=1,
    ):

        if len(scene_paths) != VISUALS_PER_SCENE:

            raise RuntimeError(
                f"Scene {scene_index} "
                f"contains {len(scene_paths)} "
                f"images instead of "
                f"{VISUALS_PER_SCENE}."
            )

        for visual_index, path in enumerate(
            scene_paths,
            start=1,
        ):

            if not os.path.exists(
                path
            ):

                raise RuntimeError(
                    f"Missing generated image: "
                    f"Scene {scene_index}, "
                    f"Shot {visual_index}: "
                    f"{path}"
                )

            if os.path.getsize(
                path
            ) < MIN_IMAGE_BYTES:

                raise RuntimeError(
                    f"Generated image is too small: "
                    f"{path}"
                )

    # ==========================================================================
    # SUMMARY
    # ==========================================================================

    print("=" * 80)
    print("✅ VISUAL GENERATION COMPLETE")
    print("=" * 80)

    print(
        f"Scenes: "
        f"{len(image_paths)}"
    )

    print(
        f"Images generated: "
        f"{total_images}"
    )

    print(
        f"Expected images: "
        f"{EXPECTED_TOTAL_IMAGES}"
    )

    print(
        f"Resolution: "
        f"{width}x{height}"
    )

    print("=" * 80)

    return image_paths


# ==========================================================================
# OPTIONAL SINGLE IMAGE HELPER
# ==========================================================================

def generate_single_image(
    prompt,
    workdir,
    filename="generated.png",
    width=DEFAULT_WIDTH,
    height=DEFAULT_HEIGHT,
    seed=None,
):
    """
    Generate one standalone image.
    """

    os.makedirs(
        workdir,
        exist_ok=True,
    )

    if seed is None:

        seed = int(
            time.time()
        )

    prompt = _clean_prompt(
        prompt
    )

    if not prompt:

        raise RuntimeError(
            "Cannot generate image "
            "with an empty prompt."
        )

    image = generate_image(
        prompt,
        width,
        height,
        seed,
    )

    path = os.path.join(
        workdir,
        filename,
    )

    _save_image(
        image,
        path,
    )

    return path