"""Movie Trivia Shorts pipeline.

Isolated production line: PlayPhrase clips + Kokoro narration.
This pipeline intentionally requires caller-supplied PlayPhrase clip URLs and
trivia copy; it does not scrape PlayPhrase or silently substitute stock media.
"""

import json
import os
import subprocess
import tempfile
from pathlib import Path

import requests

from tts import synthesize_narration


ROOT = Path(__file__).resolve().parent


def run(cmd):
    print("$", " ".join(str(x) for x in cmd))
    subprocess.run(cmd, check=True)


def download(url: str, path: Path):
    response = requests.get(url, timeout=60, headers={"User-Agent": "Mint-YT-Factory/movie-trivia"})
    response.raise_for_status()
    path.write_bytes(response.content)
    if path.stat().st_size < 1024:
        raise RuntimeError(f"Downloaded clip is empty: {url}")


def make_card(text: str, output: Path, duration: float = 2.5):
    # A simple, dependency-light title card generated by ffmpeg.
    safe = text.replace("'", "\\'").replace(":", "\\:")
    run([
        "ffmpeg", "-y", "-f", "lavfi", "-i",
        "color=c=black:s=1080x1920:r=30", "-t", str(duration),
        "-vf", f"drawtext=text='{safe}':fontcolor=white:fontsize=64:x=(w-text_w)/2:y=(h-text_h)/2:line_spacing=18",
        "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p", str(output),
    ])


def main():
    if os.getenv("PLAYPHRASE_LICENSE_ACK", "").lower() != "true":
        raise RuntimeError("Set PLAYPHRASE_LICENSE_ACK=true only when you have the required clip rights.")

    title = os.getenv("MOVIE_TITLE", "Untitled Movie").strip()
    hook = os.getenv("MOVIE_HOOK", "Did you notice this detail?").strip()
    narration = os.getenv("MOVIE_NARRATION", "").strip()
    clip_urls = [item.strip() for item in os.getenv("PLAYPHRASE_CLIP_URLS", "").split(",") if item.strip()]
    if not narration or not clip_urls:
        raise RuntimeError("MOVIE_NARRATION and PLAYPHRASE_CLIP_URLS are required.")

    output_dir = Path(os.getenv("MOVIE_OUTPUT_DIR", "artifacts/movie-trivia"))
    output_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="movie-trivia-") as temp:
        work = Path(temp)
        card = work / "hook.mp4"
        make_card(hook, card)

        clips = []
        for index, url in enumerate(clip_urls, start=1):
            clip = work / f"clip-{index}.mp4"
            download(url, clip)
            clips.append(clip)

        audio = work / "narration.mp3"
        config = {"voice": {"provider": "kokoro", "voice_name": os.getenv("MINT_KOKORO_VOICE", "af_heart"), "kokoro_lang": os.getenv("MINT_KOKORO_LANG", "a"), "speed": 1.0}}
        synthesize_narration(narration, config, str(audio), target_duration=42.0)

        concat_file = work / "concat.txt"
        concat_file.write_text("\n".join(f"file '{path.as_posix()}'" for path in [card, *clips]), encoding="utf-8")
        joined = work / "joined.mp4"
        run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(concat_file), "-c", "copy", str(joined)])

        output = output_dir / "movie-trivia-short.mp4"
        run([
            "ffmpeg", "-y", "-i", str(joined), "-i", str(audio), "-map", "0:v:0", "-map", "1:a:0",
            "-vf", "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920",
            "-t", "60", "-r", "30", "-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k", "-shortest", str(output),
        ])

    metadata = {"movie": title, "clip_source": "PlayPhrase (caller-supplied URLs)", "narration_provider": "Kokoro", "rights_acknowledged": True}
    (output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"MOVIE_TRIVIA_OUTPUT={output}")


if __name__ == "__main__":
    main()
