"""
verify_claims.py
Mint-YT-Factory

Version 2.1

Scientific claim verification layer.

FLOW:

Generated Script
      ↓
Extract IMPORTANT factual claims
      ↓
Use only scene-cited research sources
      ↓
Compare against verified Evidence Text
      ↓
Gemini evaluates support
      ↓
Local citation + evidence validation
      ↓
PASS / FAIL
      ↓
Only verified scripts continue

IMPORTANT:

- Gemini may ONLY use supplied Evidence Text.
- Metadata is NEVER treated as scientific evidence.
- Claims must use source IDs cited by their scene.
- Claims cannot switch to an unrelated source.
- Every important factual claim must have a valid citation.
- Every cited source must be evidence-verified.
- Evidence Text must actually exist.
- Uncertain claims FAIL.
- Unsupported claims FAIL.
- Contradicted claims FAIL.
- Invalid source IDs FAIL.
- Claims with zero source IDs FAIL.
- A scene does NOT need to contain a factual claim.
- Abstracts are accepted only when they are part of the verified
  research evidence package.
- Gemini cannot introduce outside knowledge.
- Original research source IDs are preserved exactly.
"""

import json
import os
import re

from google import genai
from google.genai import types


# ==========================================================================
# CONFIG
# ==========================================================================

MODEL_NAME = "gemini-flash-lite-latest"

MAX_CLAIMS_PER_SCENE = 8

MIN_EVIDENCE_CHARACTERS = 120


# ==========================================================================
# HELPERS
# ==========================================================================

def _clean(
    text
):

    if text is None:

        return ""

    return re.sub(
        r"\s+",
        " ",
        str(text),
    ).strip()


def _get_api_key():

    api_key = os.environ.get(
        "GEMINI_API_KEY"
    )

    if not api_key:

        raise RuntimeError(
            "GEMINI_API_KEY environment "
            "variable is missing."
        )

    return api_key


# ==========================================================================
# BUILD VERIFIED SOURCE MAP
# ==========================================================================

def _build_source_map(
    research
):
    """
    Build the authoritative source map.

    IMPORTANT:

    The source_id generated by the research layer is authoritative.

    Examples:

        doi_a0e748e41dd1
        doi_ad9aa1dac2e2
        doi_7566a56dbcf2
        doi_e5061afccac8
        doi_0b195db04e43

    DO NOT create artificial IDs such as:

        source_1
        source_2
        source_3

    The exact same source_id must travel through:

        research
            ↓
        script
            ↓
        scene source_ids
            ↓
        claim verification

    This prevents citation mismatches between the generated script
    and the research package.
    """

    sources = research.get(
        "sources",
        [],
    )

    source_map = {}

    for source in sources:

        if not isinstance(
            source,
            dict,
        ):

            continue

        # --------------------------------------------------------------
        # USE THE ORIGINAL RESEARCH SOURCE ID
        # --------------------------------------------------------------

        source_id = _clean(
            source.get(
                "source_id",
                "",
            )
        )

        if not source_id:

            continue

        source_map[
            source_id
        ] = source

    return source_map


# ==========================================================================
# BUILD RESEARCH EVIDENCE
# ==========================================================================

def _build_research_evidence(
    research
):
    """
    Build the evidence package Gemini is allowed to use.

    ONLY evidence-verified sources are presented as usable evidence.

    Metadata is explicitly separated from Evidence Text.
    """

    source_map = _build_source_map(
        research
    )

    blocks = []

    for source_id, source in source_map.items():

        title = _clean(
            source.get(
                "title",
                "",
            )
        )

        authors = _clean(
            source.get(
                "authors",
                "",
            )
        )

        journal = _clean(
            source.get(
                "journal",
                "",
            )
        )

        year = source.get(
            "year",
            "",
        )

        doi = _clean(
            source.get(
                "doi",
                "",
            )
        )

        evidence_text = _clean(
            source.get(
                "evidence_text",
                "",
            )
        )

        evidence_type = _clean(
            source.get(
                "evidence_type",
                "",
            )
        )

        evidence_quality = _clean(
            source.get(
                "evidence_quality",
                "",
            )
        )

        evidence_available = (
            source.get(
                "evidence_available",
                False,
            )
        )

        evidence_verified = (
            source.get(
                "evidence_verified",
                False,
            )
        )

        verification_level = _clean(
            source.get(
                "verification_level",
                "",
            )
        )

        # --------------------------------------------------------------
        # SAFETY GATE
        # --------------------------------------------------------------

        if evidence_verified is not True:

            continue

        if evidence_available is not True:

            continue

        if not evidence_text:

            continue

        if len(
            evidence_text
        ) < MIN_EVIDENCE_CHARACTERS:

            continue

        blocks.append(
            f"""
SOURCE ID: {source_id}

============================================================
SOURCE METADATA
============================================================

Title:
{title}

Authors:
{authors}

Journal:
{journal}

Year:
{year}

DOI:
{doi}

Verification Level:
{verification_level}

Evidence Verified:
{evidence_verified}

============================================================
SCIENTIFIC EVIDENCE
============================================================

Evidence Available:
{evidence_available}

Evidence Type:
{evidence_type}

Evidence Quality:
{evidence_quality}

Evidence Text:
{evidence_text}

============================================================
IMPORTANT
============================================================

Only the Evidence Text above may be used to support factual
claims.

The title, authors, journal, year, DOI, URL, verification level,
and evidence metadata are NOT scientific evidence.
""".strip()
        )

    if not blocks:

        return (
            "NO VERIFIED SCIENTIFIC EVIDENCE AVAILABLE."
        )

    return "\n\n".join(
        blocks
    )


# ==========================================================================
# BUILD SCRIPT CLAIM CONTEXT
# ==========================================================================

def _build_claim_context(
    script
):

    scenes = script.get(
        "scene_plan",
        [],
    )

    blocks = []

    for scene in scenes:

        if not isinstance(
            scene,
            dict,
        ):

            continue

        scene_number = scene.get(
            "scene"
        )

        narration = _clean(
            scene.get(
                "narration",
                "",
            )
        )

        source_ids = scene.get(
            "source_ids",
            [],
        )

        if not isinstance(
            source_ids,
            list,
        ):

            source_ids = []

        source_ids = [
            str(source_id).strip()
            for source_id in source_ids
            if str(source_id).strip()
        ]

        blocks.append(
            f"""
SCENE {scene_number}

Narration:
{narration}

CITED SOURCE IDS FOR THIS SCENE:
{json.dumps(source_ids)}
""".strip()
        )

    return "\n\n".join(
        blocks
    )


# ==========================================================================
# RESPONSE SCHEMA
# ==========================================================================

def build_response_schema():

    claim = {

        "type":
            "object",

        "properties": {

            "claim": {

                "type":
                    "string",
            },

            "scene": {

                "type":
                    "integer",
            },

            "source_ids": {

                "type":
                    "array",

                "items": {

                    "type":
                        "string",
                },
            },

            "status": {

                "type":
                    "string",

                "enum": [

                    "supported",

                    "unsupported",

                    "uncertain",

                    "contradicted",
                ],
            },

            "reason": {

                "type":
                    "string",
            },

            "evidence": {

                "type":
                    "string",
            },
        },

        "required": [

            "claim",

            "scene",

            "source_ids",

            "status",

            "reason",

            "evidence",
        ],
    }

    return {

        "type":
            "object",

        "properties": {

            "overall_status": {

                "type":
                    "string",

                "enum": [

                    "PASS",

                    "FAIL",
                ],
            },

            "claims": {

                "type":
                    "array",

                "items":
                    claim,
            },

            "unsupported_claims": {

                "type":
                    "array",

                "items": {

                    "type":
                        "string",
                },
            },

            "warnings": {

                "type":
                    "array",

                "items": {

                    "type":
                        "string",
                },
            },
        },

        "required": [

            "overall_status",

            "claims",

            "unsupported_claims",

            "warnings",
        ],
    }


# ==========================================================================
# SYSTEM PROMPT
# ==========================================================================

def _system_prompt():

    return """
You are a strict scientific fact checker.

Your job is NOT to rewrite the script.

Your job is to determine whether IMPORTANT FACTUAL CLAIMS in the
generated YouTube Short are actually supported by the supplied
verified scientific evidence.

============================================================
ABSOLUTE EVIDENCE RULE
============================================================

You may ONLY use the supplied SCIENTIFIC EVIDENCE text.

Do NOT use:

- general knowledge
- memory
- internet knowledge
- outside scientific knowledge
- invented evidence
- invented studies
- invented statistics
- information not contained in the supplied Evidence Text

============================================================
METADATA IS NOT EVIDENCE
============================================================

Never use:

- title
- authors
- journal
- year
- DOI
- URL
- verification level
- evidence type
- evidence quality

as proof of a scientific claim.

Only Evidence Text can support a scientific claim.

============================================================
IMPORTANT CLAIM EXTRACTION
============================================================

Extract EVERY IMPORTANT FACTUAL CLAIM from the narration.

Examples of factual claims:

- how something works
- what causes something
- what happens
- measurable effects
- scientific observations
- biological mechanisms
- physical mechanisms
- historical facts
- dates
- numbers
- percentages
- research findings
- relationships between variables
- scientific conclusions

Do NOT create artificial claims from storytelling language.

For example:

"Here's where it gets interesting."

is NOT a factual claim.

"Nature has another surprise."

is NOT a factual claim.

But:

"Pressure increases by about one atmosphere every ten meters."

IS a factual claim.

============================================================
SCENE CITATION RULE
============================================================

Every scene has its own cited source IDs.

For every factual claim:

- Use ONLY source IDs cited by THAT scene.
- Never substitute a source from another scene.
- Never add a source that the scene did not cite.
- The verifier source_ids MUST be a subset of the scene's
  source_ids.
- Preserve source IDs EXACTLY as provided.

Example:

Scene cites:

["doi_a0e748e41dd1", "doi_ad9aa1dac2e2"]

If the first source supports the claim:

source_ids:
["doi_a0e748e41dd1"]

If neither supports it:

status:
"unsupported"

============================================================
STATUS DEFINITIONS
============================================================

supported:
The supplied Evidence Text directly supports the claim.

uncertain:
The supplied Evidence Text is related but insufficient to establish
the claim confidently.

unsupported:
The supplied Evidence Text does not support the claim.

contradicted:
The supplied Evidence Text conflicts with the claim.

============================================================
DO NOT STRENGTHEN SCIENTIFIC LANGUAGE
============================================================

Research:

"may contribute"

Claim:

"causes"

Result:

NOT SUPPORTED.

Research:

"associated with"

Claim:

"causes"

Result:

NOT SUPPORTED.

Research:

"hypothesis"

Claim:

"proven fact"

Result:

NOT SUPPORTED.

Research:

"was observed"

Claim:

"always occurs"

Result:

NOT SUPPORTED.

Research:

"could potentially explain"

Claim:

"explains"

Result:

NOT SUPPORTED unless the Evidence Text explicitly supports
the stronger statement.

============================================================
NUMBERS
============================================================

Every number, percentage, measurement, date, quantity, or statistic
must be supported by the supplied Evidence Text.

Do not infer or calculate additional numbers unless the calculation
is directly and unambiguously supported by the supplied evidence.

============================================================
CAUSATION
============================================================

Do not convert:

- correlation → causation
- association → causation
- possibility → certainty
- hypothesis → established fact
- observation → universal rule

============================================================
CLAIM CITATION REQUIREMENT
============================================================

Every important factual claim MUST have at least one source ID.

If a factual claim has zero source IDs:

FAIL it.

If a claim uses an invalid source ID:

FAIL it.

If a claim uses a source ID that was not cited by its scene:

FAIL it.

============================================================
STYLISTIC STATEMENTS
============================================================

Statements such as:

"Here's where it gets interesting."

"This is where things change."

"Nature has another surprise."

"That makes the story even stranger."

do NOT require scientific evidence.

A scene may contain ZERO factual claims.

A scene with zero factual claims is NOT automatically a failure.

============================================================
EVIDENCE FIELD
============================================================

For every supported claim, provide a concise explanation of the
specific supplied Evidence Text that supports it.

Do NOT invent quotations.

Do NOT claim that evidence says something it does not say.

============================================================
PASS CONDITION
============================================================

PASS is allowed only when:

1. Every important factual claim was extracted.
2. Every important factual claim is supported.
3. No important claim is contradicted.
4. No important claim is unsupported.
5. No important claim is uncertain.
6. Every factual claim has valid source IDs.
7. Every factual claim's source IDs belong to that scene.
8. The narration does not exaggerate the Evidence Text.
9. Numbers and quantitative claims are supported.
10. Causal language is supported.
11. No outside knowledge was required.

Return ONLY valid JSON.
"""


# ==========================================================================
# VERIFY WITH GEMINI
# ==========================================================================

def _verify_with_gemini(
    script,
    research,
):

    client = genai.Client(
        api_key=_get_api_key()
    )

    research_evidence = (
        _build_research_evidence(
            research
        )
    )

    claim_context = (
        _build_claim_context(
            script
        )
    )

    prompt = f"""
VERIFY THIS SCRIPT.

============================================================
VERIFIED SCIENTIFIC EVIDENCE
============================================================

{research_evidence}

============================================================
SCRIPT
============================================================

{claim_context}

============================================================
TASK
============================================================

Extract EVERY IMPORTANT FACTUAL CLAIM from the narration.

Do NOT invent claims.

Do NOT turn stylistic sentences into factual claims.

For each important factual claim:

1. State the claim.
2. Identify its scene.
3. Look ONLY at Evidence Text belonging to sources cited by
   that scene.
4. Do NOT use metadata as evidence.
5. Return source_ids that are a SUBSET of the scene's cited sources.
6. Preserve the exact source IDs supplied by the research package.
7. Determine whether the evidence directly supports the claim.
8. Explain why.
9. Provide a concise evidence-based explanation.

IMPORTANT:

Do NOT use a source from another scene.

Do NOT introduce outside information.

Do NOT invent evidence.

Do NOT upgrade uncertainty into certainty.

Do NOT convert correlation into causation.

Do NOT convert possibility into certainty.

Do NOT accept unsupported numbers.

If a scene contains only stylistic narration and no factual claim,
do not create an artificial claim.

Return ONLY JSON.
"""

    response = client.models.generate_content(

        model=MODEL_NAME,

        contents=prompt,

        config=types.GenerateContentConfig(

            system_instruction=
                _system_prompt(),

            response_mime_type=
                "application/json",

            response_json_schema=
                build_response_schema(),
        ),
    )

    if not response.text:

        raise RuntimeError(
            "Claim verifier returned an empty response."
        )

    try:

        return json.loads(
            response.text
        )

    except json.JSONDecodeError as error:

        raise RuntimeError(
            "Claim verifier returned invalid JSON: "
            f"{error}"
        )


# ==========================================================================
# LOCAL SAFETY VALIDATION
# ==========================================================================

def _local_validate(
    result,
    script,
    research,
):
    """
    Local safety layer.

    Gemini decides whether the evidence supports the claim.

    This function verifies that Gemini obeyed the structural rules.

    Gemini cannot bypass:

    - invalid source IDs
    - cross-scene citations
    - missing citations
    - unverified evidence
    - missing evidence text
    - uncertain status
    - unsupported status
    - contradicted status
    """

    if not isinstance(
        result,
        dict,
    ):

        raise RuntimeError(
            "Claim verifier returned "
            "an invalid result."
        )

    # ----------------------------------------------------------------------
    # AUTHORITATIVE SOURCE MAP
    # ----------------------------------------------------------------------

    source_map = _build_source_map(
        research
    )

    valid_source_ids = set(
        source_map.keys()
    )

    # ----------------------------------------------------------------------
    # VERIFY EVERY RESEARCH SOURCE IS ACTUALLY USABLE
    # ----------------------------------------------------------------------

    usable_source_ids = set()

    for source_id, source in source_map.items():

        if not isinstance(
            source,
            dict,
        ):

            continue

        if source.get(
            "evidence_verified"
        ) is not True:

            continue

        if source.get(
            "evidence_available"
        ) is not True:

            continue

        evidence_text = _clean(
            source.get(
                "evidence_text",
                "",
            )
        )

        if len(
            evidence_text
        ) < MIN_EVIDENCE_CHARACTERS:

            continue

        usable_source_ids.add(
            source_id
        )

    # ----------------------------------------------------------------------
    # BUILD SCENE → CITED SOURCES MAP
    # ----------------------------------------------------------------------

    scene_source_map = {}

    for scene in script.get(
        "scene_plan",
        [],
    ):

        if not isinstance(
            scene,
            dict,
        ):

            continue

        scene_number = scene.get(
            "scene"
        )

        source_ids = scene.get(
            "source_ids",
            [],
        )

        if not isinstance(
            source_ids,
            list,
        ):

            source_ids = []

        normalized_ids = set(

            str(source_id).strip()

            for source_id in source_ids

            if str(source_id).strip()
        )

        scene_source_map[
            scene_number
        ] = normalized_ids

    # ----------------------------------------------------------------------
    # RESULT ARRAYS
    # ----------------------------------------------------------------------

    claims = result.get(
        "claims",
        [],
    )

    if not isinstance(
        claims,
        list,
    ):

        claims = []

    unsupported = list(
        result.get(
            "unsupported_claims",
            [],
        )
        or []
    )

    warnings = list(
        result.get(
            "warnings",
            [],
        )
        or []
    )

    # ----------------------------------------------------------------------
    # CLAIM VALIDATION
    # ----------------------------------------------------------------------

    claims_per_scene = {}

    for claim in claims:

        if not isinstance(
            claim,
            dict,
        ):

            unsupported.append(
                "Verifier returned an invalid claim object."
            )

            continue

        claim_text = _clean(
            claim.get(
                "claim",
                "",
            )
        )

        if not claim_text:

            unsupported.append(
                "Verifier returned an empty claim."
            )

            continue

        try:

            scene_number = int(
                claim.get(
                    "scene",
                    0,
                )
            )

        except Exception:

            scene_number = 0

        status = _clean(
            claim.get(
                "status",
                "",
            )
        ).lower()

        reason = _clean(
            claim.get(
                "reason",
                "",
            )
        )

        evidence = _clean(
            claim.get(
                "evidence",
                "",
            )
        )

        source_ids = claim.get(
            "source_ids",
            [],
        )

        if not isinstance(
            source_ids,
            list,
        ):

            source_ids = []

        source_ids = [

            str(source_id).strip()

            for source_id in source_ids

            if str(source_id).strip()
        ]

        # --------------------------------------------------------------
        # CLAIM COUNT
        # --------------------------------------------------------------

        claims_per_scene[
            scene_number
        ] = (
            claims_per_scene.get(
                scene_number,
                0,
            )
            + 1
        )

        if (
            claims_per_scene[
                scene_number
            ]
            > MAX_CLAIMS_PER_SCENE
        ):

            unsupported.append(
                (
                    f"Scene {scene_number} has more than "
                    f"{MAX_CLAIMS_PER_SCENE} claims."
                )
            )

        # --------------------------------------------------------------
        # SCENE MUST EXIST
        # --------------------------------------------------------------

        if scene_number not in scene_source_map:

            unsupported.append(
                (
                    f"Claim references invalid scene "
                    f"{scene_number}: {claim_text}"
                )
            )

            continue

        scene_sources = scene_source_map[
            scene_number
        ]

        # --------------------------------------------------------------
        # CLAIM MUST HAVE CITATION
        # --------------------------------------------------------------

        if not source_ids:

            unsupported.append(
                (
                    f"Claim has no source citation: "
                    f"{claim_text}"
                )
            )

        # --------------------------------------------------------------
        # SOURCE IDS MUST EXIST
        # --------------------------------------------------------------

        invalid_ids = [

            source_id

            for source_id in source_ids

            if source_id not in valid_source_ids
        ]

        if invalid_ids:

            unsupported.append(
                (
                    f"Invalid source citation "
                    f"{', '.join(invalid_ids)}: "
                    f"{claim_text}"
                )
            )

        # --------------------------------------------------------------
        # SOURCES MUST BE USABLE EVIDENCE SOURCES
        # --------------------------------------------------------------

        unusable_ids = [

            source_id

            for source_id in source_ids

            if source_id not in usable_source_ids
        ]

        if unusable_ids:

            unsupported.append(
                (
                    f"Claim uses source(s) without verified "
                    f"evidence: "
                    f"{', '.join(unusable_ids)}. "
                    f"Claim: {claim_text}"
                )
            )

        # --------------------------------------------------------------
        # SOURCE IDS MUST BELONG TO THAT SCENE
        # --------------------------------------------------------------

        wrong_scene_sources = [

            source_id

            for source_id in source_ids

            if source_id not in scene_sources
        ]

        if wrong_scene_sources:

            unsupported.append(
                (
                    f"Claim uses source(s) not cited by "
                    f"scene {scene_number}: "
                    f"{', '.join(wrong_scene_sources)}. "
                    f"Claim: {claim_text}"
                )
            )

        # --------------------------------------------------------------
        # STATUS
        # --------------------------------------------------------------

        if status in {
            "unsupported",
            "contradicted",
        }:

            unsupported.append(
                claim_text
            )

        elif status == "uncertain":

            warnings.append(
                claim_text
            )

        elif status != "supported":

            unsupported.append(
                (
                    f"Claim has invalid verification status "
                    f"'{status}': {claim_text}"
                )
            )

        # --------------------------------------------------------------
        # SUPPORTED CLAIM MUST HAVE REASON + EVIDENCE
        # --------------------------------------------------------------

        if status == "supported":

            if not reason:

                unsupported.append(
                    (
                        f"Supported claim has no verification "
                        f"reason: {claim_text}"
                    )
                )

            if not evidence:

                unsupported.append(
                    (
                        f"Supported claim has no evidence "
                        f"explanation: {claim_text}"
                    )
                )

            if not source_ids:

                unsupported.append(
                    (
                        f"Supported claim has no source: "
                        f"{claim_text}"
                    )
                )

            if invalid_ids:

                unsupported.append(
                    (
                        f"Supported claim uses invalid source: "
                        f"{claim_text}"
                    )
                )

            if unusable_ids:

                unsupported.append(
                    (
                        f"Supported claim uses source without "
                        f"verified evidence: {claim_text}"
                    )
                )

            if wrong_scene_sources:

                unsupported.append(
                    (
                        f"Supported claim uses source from "
                        f"another scene: {claim_text}"
                    )
                )

    # ----------------------------------------------------------------------
    # RESEARCH ITSELF MUST HAVE MULTIPLE VERIFIED SOURCES
    # ----------------------------------------------------------------------

    if len(
        usable_source_ids
    ) < 2:

        unsupported.append(
            (
                "Research package contains fewer than "
                "2 usable evidence-verified sources."
            )
        )

    # ----------------------------------------------------------------------
    # DEDUPLICATE
    # ----------------------------------------------------------------------

    unsupported = list(
        dict.fromkeys(

            _clean(x)

            for x in unsupported

            if _clean(x)
        )
    )

    warnings = list(
        dict.fromkeys(

            _clean(x)

            for x in warnings

            if _clean(x)
        )
    )

    # ----------------------------------------------------------------------
    # FINAL STATUS
    # ----------------------------------------------------------------------

    # Warnings are failures.
    #
    # The pipeline requires zero uncertainty.

    if unsupported:

        result[
            "overall_status"
        ] = "FAIL"

    elif warnings:

        result[
            "overall_status"
        ] = "FAIL"

    else:

        result[
            "overall_status"
        ] = "PASS"

    result[
        "unsupported_claims"
    ] = unsupported

    result[
        "warnings"
    ] = warnings

    return result


# ==========================================================================
# PUBLIC API
# ==========================================================================

def verify_script_claims(
    script,
    research,
):

    if not isinstance(
        script,
        dict,
    ):

        raise RuntimeError(
            "Claim verification received "
            "an invalid script."
        )

    if not isinstance(
        research,
        dict,
    ):

        raise RuntimeError(
            "Claim verification received "
            "invalid research."
        )

    # ----------------------------------------------------------------------
    # RESEARCH MUST BE VERIFIED
    # ----------------------------------------------------------------------

    if research.get(
        "verified"
    ) is not True:

        raise RuntimeError(
            "Claim verification requires "
            "verified research."
        )

    if research.get(
        "status"
    ) != "VERIFIED":

        raise RuntimeError(
            "Claim verification requires "
            "research status VERIFIED."
        )

    # ----------------------------------------------------------------------
    # RESEARCH MUST HAVE MULTIPLE SOURCES
    # ----------------------------------------------------------------------

    sources = research.get(
        "sources",
        [],
    )

    if not isinstance(
        sources,
        list,
    ):

        raise RuntimeError(
            "Research sources are invalid."
        )

    if len(
        sources
    ) < 2:

        raise RuntimeError(
            "Claim verification requires "
            "at least 2 research sources."
        )

    print("=" * 80)
    print("🧪 SCIENTIFIC CLAIM VERIFICATION")
    print("=" * 80)

    print(
        f"Research sources: {len(sources)}"
    )

    print(
        "Evidence policy: VERIFIED EVIDENCE TEXT ONLY"
    )

    print(
        "Citation policy: SCENE-LOCAL SOURCES ONLY"
    )

    # ----------------------------------------------------------------------
    # PRINT AUTHORITATIVE SOURCE IDS
    # ----------------------------------------------------------------------

    source_map = _build_source_map(
        research
    )

    print(
        f"Authoritative source IDs: {len(source_map)}"
    )

    for source_id in source_map:

        print(
            f"  🔗 {source_id}"
        )

    # ----------------------------------------------------------------------
    # GEMINI
    # ----------------------------------------------------------------------

    result = _verify_with_gemini(
        script,
        research,
    )

    # ----------------------------------------------------------------------
    # LOCAL SAFETY VALIDATION
    # ----------------------------------------------------------------------

    result = _local_validate(
        result,
        script,
        research,
    )

    # ----------------------------------------------------------------------
    # SAVE RESULT INTO SCRIPT
    # ----------------------------------------------------------------------

    script[
        "claim_verification"
    ] = {

        "overall_status":
            result.get(
                "overall_status",
                "FAIL",
            ),

        "claims":
            result.get(
                "claims",
                [],
            ),

        "unsupported_claims":
            result.get(
                "unsupported_claims",
                [],
            ),

        "warnings":
            result.get(
                "warnings",
                [],
            ),

        "verified":
            (
                result.get(
                    "overall_status"
                )
                == "PASS"
            ),
    }

    # ----------------------------------------------------------------------
    # OUTPUT
    # ----------------------------------------------------------------------

    if result.get(
        "overall_status"
    ) == "PASS":

        print(
            "✅ ALL IMPORTANT CLAIMS VERIFIED"
        )

    else:

        print(
            "❌ CLAIM VERIFICATION FAILED"
        )

        unsupported = result.get(
            "unsupported_claims",
            [],
        )

        warnings = result.get(
            "warnings",
            [],
        )

        if unsupported:

            print(
                "\n❌ Unsupported / invalid claims:"
            )

            for claim in unsupported:

                print(
                    f"  ❌ {claim}"
                )

        if warnings:

            print(
                "\n⚠️ Uncertain claims:"
            )

            for warning in warnings:

                print(
                    f"  ⚠️ {warning}"
                )

    print("=" * 80)

    return script


# ==========================================================================
# CLAIM VERIFICATION STATUS
# ==========================================================================

def claims_are_verified(
    script,
):

    verification = script.get(
        "claim_verification",
        {},
    )

    return (

        verification.get(
            "verified"
        )
        is True

        and

        verification.get(
            "overall_status"
        )
        == "PASS"
    )


# ==========================================================================
# LOCAL TEST
# ==========================================================================

if __name__ == "__main__":

    print(
        "verify_claims.py is a pipeline module."
    )

    print(
        "It is called automatically by main.py."
    )